### ISSUE TITLE
Failure on r-universe

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/r2readthedocs#11]
Probably not mission critical but maybe good to know https://github.com/r-universe/ropensci/runs/6372526960?check_suite_focus=true

Via https://ropensci.r-universe.dev/ui#builds

**Comment by mpadge** [comment]
Yeah, the whole ecosystem has been failing on r-univ builds for last couple of days coz of pkgstats. Plus I think I'm starting to suspect that httptest2 is somehow incompatible with r-univ windows builds. Anyway, mostly  fixed/circumvented upstream now, so should hopefully propagate here soon. Thanks!

**Comment by maelle** [comment]
:+1: :pray:

**Comment by mpadge** [comment]
https://github.com/r-universe/ropensci/actions/runs/2395874148 :heavy_check_mark:
