### ISSUE TITLE
deprecation error when using r2readthedocs

### ISSUE THREAD

**Issue by abhosekar** [ropenscilabs/r2readthedocs#15]
Hi, I am running the following two commands
```
path <- rtd_dummy_pkg ()
r2readthedocs (path)
```
and I get the following error:
```
Error in file_path_as_absolute(dir) :
  'x' must be a single character string
In addition: Warning message:
'Rd2md::Rd2markdown' is deprecated.
Use 'as_markdown' instead.
See help("Deprecated") and help("Rd2md-deprecated").
```
Here is the traceback
````
> traceback()
11: stop("'x' must be a single character string")
10: file_path_as_absolute(dir)
9: .get_package_metadata(pkgdir)
8: tools::loadPkgRdMacros(pkg_path)
7: parse_rd_file(path, pkg_path)
6: read_rdfile(rdfile)
5: as_markdown(read_rdfile(rdfile))
4: cat(as_markdown(read_rdfile(rdfile)), file = outfile, append = append)
3: Rd2md::Rd2markdown(f, outfile = fout)
2: convert_man(path)
1: r2readthedocs(path)
```

I get the same error with R 4.3.2 on Windows and R 4.4 on Linux.

**Comment by mpadge** [comment]
Thanks @abhosekar for catching that. I've updated similar code [elsewhere](https://github.com/ropensci-review-tools/ropensci-review-tools/commit/20673a9a6c7a3ddbbcc955fb86bea50e2648e05a), but a smooth transition requires the `Rd2md` package to first be updated on CRAN, to incorporate [these changes](https://github.com/quantsch/Rd2md/pull/22). I'll fix here in the meantime by installing remote version of `Rd2md`, but will leave this issue open until Rd2md has been updated
